#143410117 Convert from Grunt to Gulp taskrunner
andela/muse-cards-for-humanity pull request #9
Opened 2017-04-19 13:45 UTC by Mnickii

#### What does this PR do?

Converts the tasks in grunt to run in gulp task runner
Adds a .env file
Updates .gitignore

#### Description of Task to be completed?

Have tasks such as nodemon,bower install, lint, mocha test, server automated by use of gulp task runner.

#### How should this be manually tested?

After cloning the repo, cd into it, ```$ gulp```
#### Any background context you want to provide?

The tasks were previously ran by gruntfile.js, now deleted.

#### What are the relevant pivotal tracker stories?

Grunt is an older task runner than Gulp; with Gulp, the syntax is much simpler to comprehend and it uses pipe streams which makes it inherently faster.

2017-04-19 19:29 UTC, nyambati requested changes
Your build is failing because you have not  changed the `package.json` scripts not to run grunt. Make sure that you update `package.json` accordingly. This involves removing unused packages and ensure that the new packages are recorded as dependencies.

2017-04-20 08:21 UTC, Mnickii commented
I have complete all the requested changes

2017-04-20 09:53 UTC, jm-wanja approved these changes

2017-04-20 09:53 UTC, nyambati approved these changes

2017-04-20 09:56 UTC, nyambati approved these changes

2017-04-20 10:27 UTC, nyambati approved these changes

2017-04-20 13:02 UTC, merged